# configs/sweep_config_blue_demon.yaml
program: main.py
name: ncd-gp-cn_blue-demon_GPU0
method: bayes
metric:
  name: val_loss
  goal: minimize
parameters:
  model_type:
    values: ['autoencoder', 'conv_s2s', 'transformer']
  data_path:
    value: ['data/ncd_gp_conceptnet/ncd_gp_conceptnet_train.tsv', 'data/ncd_gp_conceptnet/ncd_gp_conceptnet_valid.tsv']
  #train_data_path:
  #  values: ['data/conceptnet_gp/conceptnet_gp_train.tsv', 'data/ncd_gp_conceptnet/ncd_gp_conceptnet_train.tsv']
  #valid_data_path:
  #  distribution: categorical
  #  values: 
  #    - 'data/conceptnet_gp/conceptnet_gp_valid.tsv'
  #    - 'data/ncd_gp_conceptnet/ncd_gp_conceptnet_valid.tsv'
  batch_size:
    values: [16, 64]  # Smaller sizes for 24 GB
  learning_rate:
    values: [1e-4, 1e-3, 1e-2]
  target_seq_len:
    values: [3, 16, 64]  # Include 3 for Autoencoder
  num_epochs:
    value: 3

  autoencoder_d_model:
    values: [512, 1024]  # Moderate sizes
  autoencoder_hidden_dim:
    values: [256, 512, 1024]
  autoencoder_num_encoder_layers:
    values: [1, 2, 4]
  autoencoder_activation:
    value: 'ReLU'
  autoencoder_pe_mode:
    value: 'fixed'
  autoencoder_use_normalization:
    value: true
  autoencoder_norm_type:
    value: 'batch'

  conv_s2s_embed_dim:
    values: [512, 1024]  # Moderate sizes
  conv_s2s_hidden_dim:
    values: [256, 512, 1024]
  conv_s2s_num_layers:
    values: [2, 4, 6]
  conv_s2s_use_attention:
    values: [true, false]
  conv_s2s_kernel_size:
    value: 3

  transformer_d_model:
    values: [256, 512]  # Smaller sizes
  transformer_nhead:
    values: [4, 8]
  transformer_num_encoder_layers:
    values: [1, 2]
  transformer_num_decoder_layers:
    values: [1, 2]
  transformer_dim_feedforward:
    min: 1024
    max: 2048
  transformer_activation:
    value: 'relu'
  transformer_pe_mode:
    value: 'fixed'
  transformer_fixed_scale:
    value: 1.0
  transformer_learned_scale:
    value: 1.0
